# Generated by Django 4.2.11 on 2024-05-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('wallet', models.CharField(max_length=50)),
                ('_is_active', models.BooleanField(default=False)),
                ('bitgo_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='management.bitgowallet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='dashboard.profile')),
            ],
        ),
    ]
