# Generated by Django 4.2.11 on 2024-03-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitgoWallet',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('_type', models.CharField(choices=[('trx', 'TRON'), ('bep', 'Binance Smart Chain'), ('eth', 'Ethereum')], max_length=3)),
            ],
        ),
    ]
