# Generated by Django 4.2.11 on 2024-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitgoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(editable=False, max_length=50)),
                ('_type', models.CharField(choices=[('ttrx', 'TRON'), ('tsol', 'Solana'), ('tpolygon', 'Polygon')], max_length=20)),
            ],
        ),
    ]
