# Generated by Django 4.2.11 on 2024-03-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitgowallet',
            name='wallet_id',
            field=models.CharField(default='nothing', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitgowallet',
            name='_type',
            field=models.CharField(choices=[('ttrx', 'TRON'), ('tsol', 'Solana'), ('tpolygon', 'Polygon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitgowallet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
