# Generated by Django 4.2.11 on 2024-03-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
        migrations.AddField(
            model_name='deposit',
            name='profile',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='dashboard.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='dashboard.profile'),
            preserve_default=False,
        ),
    ]
