# Generated by Django 4.2.8 on 2024-02-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_user_services_bankmanagement', '0002_bankadminmanager_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccountdetails',
            name='account_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccountdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
