# Generated by Django 4.2.8 on 2024-03-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_user_services_bankmanagement', '0003_userbankaccountdetails_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccountdetails',
            name='account_number',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
