# Generated by Django 4.2.8 on 2024-02-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0002_user_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
